# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'program.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.num_4 = QPushButton(self.centralwidget)
        self.num_4.setObjectName(u"num_4")
        self.num_4.setGeometry(QRect(10, 120, 91, 91))
        self.num_2 = QPushButton(self.centralwidget)
        self.num_2.setObjectName(u"num_2")
        self.num_2.setGeometry(QRect(120, 20, 91, 91))
        self.num_8 = QPushButton(self.centralwidget)
        self.num_8.setObjectName(u"num_8")
        self.num_8.setGeometry(QRect(120, 230, 91, 91))
        self.mul_button = QPushButton(self.centralwidget)
        self.mul_button.setObjectName(u"mul_button")
        self.mul_button.setGeometry(QRect(10, 330, 91, 91))
        self.num_5 = QPushButton(self.centralwidget)
        self.num_5.setObjectName(u"num_5")
        self.num_5.setGeometry(QRect(120, 120, 91, 91))
        self.sub_button = QPushButton(self.centralwidget)
        self.sub_button.setObjectName(u"sub_button")
        self.sub_button.setGeometry(QRect(220, 330, 91, 91))
        self.num_6 = QPushButton(self.centralwidget)
        self.num_6.setObjectName(u"num_6")
        self.num_6.setGeometry(QRect(220, 120, 91, 91))
        self.num_0 = QPushButton(self.centralwidget)
        self.num_0.setObjectName(u"num_0")
        self.num_0.setGeometry(QRect(120, 330, 91, 91))
        self.delete_button = QPushButton(self.centralwidget)
        self.delete_button.setObjectName(u"delete_button")
        self.delete_button.setGeometry(QRect(480, 190, 141, 81))
        self.num_3 = QPushButton(self.centralwidget)
        self.num_3.setObjectName(u"num_3")
        self.num_3.setGeometry(QRect(220, 20, 91, 91))
        self.num_1 = QPushButton(self.centralwidget)
        self.num_1.setObjectName(u"num_1")
        self.num_1.setGeometry(QRect(10, 20, 91, 91))
        self.num_7 = QPushButton(self.centralwidget)
        self.num_7.setObjectName(u"num_7")
        self.num_7.setGeometry(QRect(10, 230, 91, 91))
        self.num_9 = QPushButton(self.centralwidget)
        self.num_9.setObjectName(u"num_9")
        self.num_9.setGeometry(QRect(220, 230, 91, 91))
        self.output_text = QLineEdit(self.centralwidget)
        self.output_text.setObjectName(u"output_text")
        self.output_text.setGeometry(QRect(320, 20, 471, 161))
        font = QFont()
        font.setPointSize(22)
        self.output_text.setFont(font)
        self.add_button = QPushButton(self.centralwidget)
        self.add_button.setObjectName(u"add_button")
        self.add_button.setGeometry(QRect(220, 430, 91, 91))
        self.pow_button = QPushButton(self.centralwidget)
        self.pow_button.setObjectName(u"pow_button")
        self.pow_button.setGeometry(QRect(120, 430, 91, 91))
        self.divide_button = QPushButton(self.centralwidget)
        self.divide_button.setObjectName(u"divide_button")
        self.divide_button.setGeometry(QRect(10, 430, 91, 91))
        self.clear_button = QPushButton(self.centralwidget)
        self.clear_button.setObjectName(u"clear_button")
        self.clear_button.setGeometry(QRect(330, 190, 131, 81))
        self.calculate_button = QPushButton(self.centralwidget)
        self.calculate_button.setObjectName(u"calculate_button")
        self.calculate_button.setGeometry(QRect(640, 190, 141, 81))
        self.tan_button = QPushButton(self.centralwidget)
        self.tan_button.setObjectName(u"tan_button")
        self.tan_button.setGeometry(QRect(640, 290, 141, 81))
        self.cos_button = QPushButton(self.centralwidget)
        self.cos_button.setObjectName(u"cos_button")
        self.cos_button.setGeometry(QRect(480, 290, 141, 81))
        self.sin_button = QPushButton(self.centralwidget)
        self.sin_button.setObjectName(u"sin_button")
        self.sin_button.setGeometry(QRect(330, 290, 131, 81))
        self.factorial_button = QPushButton(self.centralwidget)
        self.factorial_button.setObjectName(u"factorial_button")
        self.factorial_button.setGeometry(QRect(330, 400, 131, 81))
        self.invert_button = QPushButton(self.centralwidget)
        self.invert_button.setObjectName(u"invert_button")
        self.invert_button.setGeometry(QRect(640, 400, 141, 81))
        self.sqrt_button = QPushButton(self.centralwidget)
        self.sqrt_button.setObjectName(u"sqrt_button")
        self.sqrt_button.setGeometry(QRect(480, 400, 141, 81))
        self.sum_button = QPushButton(self.centralwidget)
        self.sum_button.setObjectName(u"sum_button")
        self.sum_button.setGeometry(QRect(360, 490, 391, 61))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.num_4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.num_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.num_8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.mul_button.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.num_5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.sub_button.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.num_6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.num_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.delete_button.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.num_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.num_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.num_7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.num_9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.add_button.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pow_button.setText(QCoreApplication.translate("MainWindow", u"^", None))
        self.divide_button.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.clear_button.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.calculate_button.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.tan_button.setText(QCoreApplication.translate("MainWindow", u"tan", None))
        self.cos_button.setText(QCoreApplication.translate("MainWindow", u"cos", None))
        self.sin_button.setText(QCoreApplication.translate("MainWindow", u"sin", None))
        self.factorial_button.setText(QCoreApplication.translate("MainWindow", u"factorial", None))
        self.invert_button.setText(QCoreApplication.translate("MainWindow", u"1/x", None))
        self.sqrt_button.setText(QCoreApplication.translate("MainWindow", u"sqrt", None))
        self.sum_button.setText(QCoreApplication.translate("MainWindow", u"Summarize", None))
    # retranslateUi

